name: settings_yaml
version: 2.1.0
homepage: https://github.com/bsutton/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  meta: ^1.0.0
  yaml: ^2.2.0
  path: ^1.0.0
  uuid: ^1.0.0
dev_dependencies: 
  test: ^1.0.0
  pedantic: ^1.9.0
